version: "3.8"

# docker-compose up --build

services:
  personal_assistant:
    image: personal_assistant
    container_name: personal_assistant
    build:
      context: .
      dockerfile: Dockerfile.test
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./src:/code
